  WE REMOVED ALL THE FILES IN THIS REPOSITORY BECAUSE THERE WAS AN ERROR IN THIS FOLDER. VUE WOULD CAUSE OUR PROJECT TO FAIL.
WHEN PUTTING THIS FOLDER AND A FOLDER(1) CONTAINING THE SAME EXACT CODE SIDE BY SIDE RUNNING ON PY4WEB, THIS FOLDER WOULD FAIL WHILE THE 
FOLDER 1 WOULD SUCCEED. WE DETERMINED THIS ISSUE TO BE BECAUSE OF THIS GIT REPOSITORY, SO IN AN ATTEMPT TO FIX IT, WE DELETED THE FILES OF THIS REPOSITORY
AND MOVED IT ONTO A DIFFERENT REPOSITORY.

THIS IS THE NEW REPOSITORY FOR WHICH AFTER ADDING IT INTO A DIFFERENT REPOSITORY, WAS SUCCESSFUL.

https://github.com/niecoope/CSE183_Project_2nd_Repo
